import:
  - ~/.config/awesome/apps/alacritty/colors/rose-pine.yml

font:
  normal:
    family: Iosevka Nerd Font
    # family: SAGA
    # family: FantasqueSansMono Nerd Font
    # family: JetBrainsMono Nerd Font
    # family: Victor Mono Nerd Font
    # style: Medium Italic
  size: 16

window:
  padding:
    x: 50
    y: 50
    dynamic_padding: false

live_config_reload: true

cursor:
  style: Beam
  vi_style_cursor: Beam

env:
  TERM: xterm-256color
